version: '3.3'

services:
  api:
    build: .
    container_name: socialnet-api
    command: ./docker-entrypoint.sh
    restart: unless-stopped
    ports:
      - "8003:8003"
    depends_on:
      - redis
      - postgres
    volumes:
      - .:/socialnet-app

  postgres:
    image: postgres:15.3-alpine3.18
    container_name: socialnet-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    env_file:
      - src/db/conf/db
    environment:
      PGDATA: "/var/lib/postgresql/data/pg_data"
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7.0.11-alpine3.18
    container_name: socialnet-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_cache:/data

networks:
  socialnet-app:

volumes:
  pg_data:
  redis_cache:
